### ISSUE TITLE
body animation still doesn't work

### ISSUE THREAD

**Issue by lomovoyPlayer** [VentureCraftMods/MC-Gliders#11]
body animation still doesn't work

**Comment by Suff99** [comment]
This gives me no information or context. Attach videos or screenshots.

**Comment by lomovoyPlayer** [comment]
I've already done it and nothing has changed, except that the glider has become much less likely to get stuck in the folded state, the character also seems to be standing and not even raising his hands

https://user-images.githubusercontent.com/102898719/221166372-16079786-3c5f-482a-9741-58dbe05d9deb.mp4

**Comment by Suff99** [comment]
I see - do you have other animation based mods installed?

**Comment by lomovoyPlayer** [comment]
> I see - do you have other animation based mods installed?

player-animation-lib-fabric

**Comment by Suff99** [comment]
Do you need that for other mods you have installed?

**Comment by lomovoyPlayer** [comment]
for two already installed (on which some others depend) and two more are planned for installation

**Comment by lomovoyPlayer** [comment]
better combat, Combat Roll, Emotecraft, Kelvin's Better Player Animations

**Comment by BLUEChester** [comment]
the same issue is also occuring for me

**Comment by Suff99** [comment]
Will be solved when we move to Player Animation Lib
