### ISSUE TITLE
Durability issue and some suggestion

### ISSUE THREAD

**Issue by Athurrender** [VentureCraftMods/MC-Gliders#13]
The durability of these gliders seems to be wrong.
leather one is 500 for now, iron is 80, gold is 200, diamond is 100 and the netherite is 500.Guess they're mixed up.
If leather is 100, iron is 200, gold is 300, diamond is 500 and the netherite is 600, that would be reasonable and great.
And could you make the gilders to be repairable by using their crafting materials like leather, iron ingots and so on?

**Comment by Suff99** [comment]
https://github.com/VentureCraftMods/MC-Gliders/issues/27
