### ISSUE TITLE
[Suggestion] Option to disable automatic third-person switch

### ISSUE THREAD

**Issue by Samarai** [VentureCraftMods/MC-Gliders#14]
I'm assuming the automatic third-person view when gliding is meant to help with getting a better idea of your surroundings, plus to show off the pretty animations (and they are quite pretty!), but it'd be nice to have the ability to disable it. Using the F5 key to put yourself back in first-person shows that the gliders work just fine from that perspective, even when using a mod like tr9zw's [First-person Model](https://www.curseforge.com/minecraft/mc-mods/first-person-model) mod that renders your body from the first person view, it just also boots you into third-person upon landing.

**Comment by Suff99** [comment]
Please see the options key bindings menu

**Comment by Samarai** [comment]
> Please see the options key bindings menu

Oh jeez, I'm a buffoon- sorry about that, didn't think to check there!
