### ISSUE TITLE
Unintended glider use

### ISSUE THREAD

**Issue by JLUsr** [VentureCraftMods/MC-Gliders#15]
Sometimes the glider will use itself/activate when a player jumps whilst standing on a surface made of slabs that occupy the lower half of the block they would otherwise make up. For consistency's sake, it was easiest to reproduce when making a platform that was 4x4 with a few air blocks below it. This can also happen when the player shift walks to the very edge of a block (making the player appear as though they are standing in the air) and jumps, I had been a little confused for a while thinking my spacebar was just being finicky whilst doing some tree parkour.

**Comment by Suff99** [comment]
Covered by https://github.com/VentureCraftMods/MC-Gliders/issues/27
