### ISSUE TITLE
Immersive first person incompatibility  

### ISSUE THREAD

**Issue by tehehe22** [VentureCraftMods/MC-Gliders#18]
its a overlay of the first person animation
![2023-02-27_19 35 32](https://user-images.githubusercontent.com/123723090/223295070-9800a143-ac47-4251-b6eb-cd84a600963f.png)

**Comment by Suff99** [comment]
Will likely be solved by https://github.com/VentureCraftMods/MC-Gliders/issues/20

Please re-open if this is not the case upon release

**Comment by tehehe22** [comment]
idk why I didn't test it but it's still broken
