### ISSUE TITLE
[Suggestion] Cape slot + other little things

### ISSUE THREAD

**Issue by 42Cyborg** [VentureCraftMods/MC-Gliders#19]
I am making a data pack and I absolutely love this mod, but I have some other trinkets mods already set up to use the back slot and for balancing, I would really like to be able to allow these gliders to be put in the "cape" slot instead (or as well as) the back slot.

Short-term: It would be great to have it work in the "cape" trinkets slot as well

Long-term: I don't know if it is feasible but I would love to see a config with an option to select what slot the glider goes in, and maybe an option  to change the durabilities

**Comment by Jusey1** [comment]
I would prefer it to work in the Back slot (it seems to have it's own slot right now but I assume it can work in any curios slot so I can change that up with configs/datapack).

**Comment by Suff99** [comment]
Done
