### ISSUE TITLE
(Suggestion) Option to not switch to 3rd person with using glider

### ISSUE THREAD

**Issue by tehehe22** [VentureCraftMods/MC-Gliders#2]
I don't think it's supposed to do this but my glider makes my game go into 3rd person automatically, and also for the first person do u think you can make that little animation thing invisible as an option because it conflicts with immersive first person.

**Comment by Suff99** [comment]
Please see your controls keybind:
![2023-02-19_14 14 54](https://user-images.githubusercontent.com/36424503/219953816-2f635b9b-28c7-41be-9041-7ee4ed8d5452.png)

I can make a config option for the first person rendering for sure - but can you show me a video on a separate issue with the issue it creates? Thanks
