### ISSUE TITLE
ConcurrentModificationException on CLIENT_SETUP due to ItemProperties::register (Forge, Minecraft 19.2)

### ISSUE THREAD

**Issue by ForgottenUmbrella** [VentureCraftMods/MC-Gliders#25]
This mod occasionally throws a `ConcurrentModificationException` on Forge when installed with other mods that don't handle `ItemProperties::register` properly, as that method is not thread-safe. This isn't due to code in this mod itself, but rather the [PalladiumCore library that it depends on](https://github.com/ThreeTAG/PalladiumCore/issues/1#issuecomment-1528716353).

To fix this bug, you'll need to update your dependency on PalladiumCore to 1.4.1.1.

**Comment by Suff99** [comment]
Lucas has made me aware, I am just trying to find time to sort that out
