### ISSUE TITLE
Allow for ResourcePacks to modify empty Curio Slot texture.

### ISSUE THREAD

**Issue by K-Proj** [VentureCraftMods/MC-Gliders#28]
Normally changing the curio slot texture of a mod is as easy as changing a gui texture in the assets folder of a mod using a resourepack. Unless I'm missing something, I can't see this texture anywhere, which makes me believe it's being rendered an alternate way. It would be nice to modify the curio/trinket slot gui textures using a resourcepack just as modifying the glider's model and item textures can be.

**Comment by Suff99** [comment]
The texture used is found here: https://github.com/VentureCraftMods/MC-Gliders/blob/main/common/src/main/resources/assets/vc_gliders/textures/item/glider_slot.png
