### ISSUE TITLE
[Fabric/Quilt 1.19.2] Server Crash

### ISSUE THREAD

**Issue by JLUsr** [VentureCraftMods/MC-Gliders#3]
Seems to prevent a server from starting up on 1.19.2 Fabric or Quilt servers. This occurs even when no other mods are present. The following [gist](https://gist.github.com/JLUsr/788d49d8556c706d4e50911db12f7798) contains a log for both Quilt and Fabric startup failures.

**Comment by Suff99** [comment]
Fixed in 1.0.1!
