### ISSUE TITLE
[Sugestion] Parcool (Or other movement mods) integration.

### ISSUE THREAD

**Issue by Edoliviro** [VentureCraftMods/MC-Gliders#30]
Some way of not allowing the use of gliders during animations from other mods.

Or maybe making the glider cancel all actions taking place in the moment.

**Comment by Suff99** [comment]
I'm not sure I fully understand what you are asking?

**Comment by Edoliviro** [comment]
don't worry about it, it's a problem that can be fixed with a keybind to activate the glider, i was sleepy while writing the issue xD
