### ISSUE TITLE
Game crashes in 1.19.2 (Forge) (version v1.0.3)

### ISSUE THREAD

**Issue by XAURAVUS** [VentureCraftMods/MC-Gliders#32]
The mod does not load. When entering the main menu, all mods are gone and the game appears to be vanilla. The issue is resolved only with removing the mod. Gliders version v1.0.2 works.
![image](https://github.com/VentureCraftMods/MC-Gliders/assets/82698242/bcb5dd60-2da6-41a5-bb82-88271272228d)

**Comment by Suff99** [comment]
Sorted:

https://legacy.curseforge.com/minecraft/mc-mods/gliders/files/4620665
https://legacy.curseforge.com/minecraft/mc-mods/gliders/files/4620664
https://modrinth.com/mod/gliders/version/1.1.0+fabric
https://modrinth.com/mod/gliders/version/1.1.0+forge
