### ISSUE TITLE
Fabric 1.20.(1) support would be appreciated 

### ISSUE THREAD

**Issue by Zorklis** [VentureCraftMods/MC-Gliders#36]
Fabric 1.20.(1) support would be appreciated

**Comment by Suff99** [comment]
It’s going to be worked on soon

**Comment by Zorklis** [comment]
Why close it if it's not complete! What's the point of issues tab then

**Comment by Suff99** [comment]
The issues tabs purpose is to report issues such as bugs and crashes with the mod. The place to request ports and enhancements is better suited for the Discord. Imagine a issue request being opened for 1.19.3, 1.19.4, 1.20 and 1.20.1 and then imagine it going the other way
