### ISSUE TITLE
[Suggestion] Trinkets integration

### ISSUE THREAD

**Issue by iSimilaXi** [VentureCraftMods/MC-Gliders#4]
With Trinkets integration, you could use trinkets slots to equip gliders, instead of strictly torso slot.
I think it would be beneficial to the players if you implementing this, offering more flexible and seamless gameplay (no need to access inventory to switch when in-combat, or no need to keep gliders in hotbar/in-hand in case of emergency case) 

mods link: https://www.curseforge.com/minecraft/mc-mods/trinkets

**Comment by Suff99** [comment]
Added in 1.0.1
