### ISSUE TITLE
Possible compat issue with Happiness is a Warm Gun

### ISSUE THREAD

**Issue by Sunconure11** [VentureCraftMods/MC-Gliders#40]
https://github.com/cybercat-mods/HWG/issues/88

**Comment by Suff99** [comment]
User isn't gliding when they do this correct?

**Comment by Sunconure11** [comment]
Correct.

**Comment by Sunconure11** [comment]
Issue is still present.

**Comment by Suff99** [comment]
Strange, when I tested last night on a curse install, it worked just fine
I was able to walk around blasting one of the guns 

I’ll look deeper into this?

**Comment by Sunconure11** [comment]
@somekindofanimal Can you post your mod list?

**Comment by Sunconure11** [comment]
I want to compare it to mine

**Comment by jwaxy** [comment]
I am having the same issue. Is there any fixes?

**Comment by Sunconure11** [comment]
This is still present. Of note is that I'm using Quilt.
