### ISSUE TITLE
Plans for 1.20?

### ISSUE THREAD

**Issue by Junebugging** [VentureCraftMods/MC-Gliders#41]
This mod is absolutely amazingly designed, from both a game design and also a visual design aspect, amazing job! 
Are you planning on updating it for 1.20?

**Comment by TomatoPuddin** [comment]
[WIP](https://github.com/VentureCraftMods/MC-Gliders/commits/mc/1.20)

**Comment by Kerobotto** [comment]
Ill definitely use this if it ever comes to 1.20.1.
