### ISSUE TITLE
[Forge 1.19.2] Visual bug with Shaders activated using Rubidium and Oculus

### ISSUE THREAD

**Issue by PreciseModpacker** [VentureCraftMods/MC-Gliders#43]
Hi!

First of all thank you for reading this.

I saw a weird visual bug that happens when i'm using the Gliders 1.1.3, Rubidium 0.6.2b and Oculus 1.6.4 mod in Minecraft 1.19.2 Forge 43.2.0.

If you use the Paraglider while I have the Complementary Reimagined Shaders activated you can see this visual bug ![imagen](https://github.com/VentureCraftMods/MC-Gliders/assets/110386565/d975b9f3-f76b-4738-840b-ba0c4bc68071)

This can be fixed with an small workaround disablin the Real-Time Shadows
![imagen](https://github.com/VentureCraftMods/MC-Gliders/assets/110386565/3beb5970-254d-49ad-aaf9-c9dcdcc0fb99)
![imagen](https://github.com/VentureCraftMods/MC-Gliders/assets/110386565/0d3d99a1-d0e2-47de-a85a-082c366739e7)
![imagen](https://github.com/VentureCraftMods/MC-Gliders/assets/110386565/ffbcf539-cf47-4833-adff-352544e3b403)
![imagen](https://github.com/VentureCraftMods/MC-Gliders/assets/110386565/38352e7e-25d5-4b96-99f0-da9eabdc9b71)

This same bug happens with other Shaders like SuperDuperVanilla Shaderpack and it can be fixed turning off the Shadowmapping feature in this Shaderpack
![imagen](https://github.com/VentureCraftMods/MC-Gliders/assets/110386565/02016053-30de-45c3-b61d-9cffcd977769)
![imagen](https://github.com/VentureCraftMods/MC-Gliders/assets/110386565/21f077cd-c778-47cb-9dc2-0f6a25d4d323)
![imagen](https://github.com/VentureCraftMods/MC-Gliders/assets/110386565/939a1116-dd48-422e-a4c5-4d5c13663b8d)

Maybe this error happens in others shaderpack too, if you need, please tell me and i can try to give you more examples if needed.

**Comment by PreciseModpacker** [comment]
Yes I tested it and it looks that this problem doesn't happen in third person

**Comment by Suff99** [comment]
I cannot fix bugs induced by shaders or performance enhancing mods - there will be a config option in 1.20 for disabling the first person glider model which may help your issue.

**Comment by PreciseModpacker** [comment]
That it would be a good solution!
It would be possible to add this feature to 1.19.2 too? That it would be great! 👍
