### ISSUE TITLE
Repairing gliders in anvil does not work - durability does not go up

### ISSUE THREAD

**Issue by szernex** [VentureCraftMods/MC-Gliders#44]
When trying to repair an Iron Glider with Re-Inforced Paper (Iron) in an anvil the durability does not go up. It will use the paper and XP but the durability just stays the same.

https://i.vgy.me/WBhlKJ.png
https://i.vgy.me/EMSBrt.png

Minecraft 1.19.2, Fabric version 0.14.22, Mod version 1.1.3

**Comment by Suff99** [comment]
Thank you for reporting, should be a simple fix.
