### ISSUE TITLE
Glider Balancing

### ISSUE THREAD

**Issue by ByteSix** [VentureCraftMods/MC-Gliders#47]
Is it in the vision of the mod to add a resource meter? A configurable balance for players seeking more difficulty alongside the quality of life and fun the mod offers.

Something like higher hunger exhaustion upon usage, maybe preventing the paraglider to be opened for a second after it's been used and retracted, some sort of 'anti-cheeze' mechanic?

**Comment by Suff99** [comment]
There are no plans to implement a resource meter.
