### ISSUE TITLE
Set First Person After Landing

### ISSUE THREAD

**Issue by greensad** [VentureCraftMods/MC-Gliders#5]
IDK if this is a bug but currently I am locked into third person mode unless I press jump while gliding, if I land third person mode persists until I press F5. Would be great to automatically go back to first person on land. Wondering if this might be a compatibility issue with '[Auto-Third Person](https://modrinth.com/mod/auto-third-person)'.

Log: https://mclo.gs/2mGhWOA

**Comment by Suff99** [comment]
Sounds like a oversight on my part - you are actually meant to be put back into first person (or whatever perspective you previously had) when you land - Ill sort this for 1.0.1

**Comment by Suff99** [comment]
Fixed
