### ISSUE TITLE
animation doesn't work and somehow I was able to start flying as a creative

### ISSUE THREAD

**Issue by lomovoyPlayer** [VentureCraftMods/MC-Gliders#6]
![image](https://user-images.githubusercontent.com/102898719/220106597-9ad678fc-b013-4e01-b691-b74ebf4420a2.png)
I can't repeat it, but somehow at the opening of the plein air, I began to fly like in a creative
![image](https://user-images.githubusercontent.com/102898719/220107356-51406287-0797-4132-bd66-9abf937582f0.png)
![image](https://user-images.githubusercontent.com/102898719/220107416-79493db0-c051-4ea2-85cb-8b1c1efba9f7.png)
here is a list of mods
[mods.txt](https://github.com/VentureCraftMods/MC-Gliders/files/10784485/mods.txt)

**Comment by Suff99** [comment]
Will be fixed next update
