### ISSUE TITLE
Crash when on server

### ISSUE THREAD

**Issue by vivagabe** [VentureCraftMods/MC-Gliders#7]
Awesome mod! Unfortunately it seems to crash when i use it on my server:
[debug.log](https://github.com/VentureCraftMods/MC-Gliders/files/10789756/debug.log)

I have a lot of mods but it seems like vc gliders is the one crashing the server.

**Comment by Suff99** [comment]
Duplicate: https://github.com/VentureCraftMods/MC-Gliders/issues/3
