### ISSUE TITLE
Crash on startup (crashlog included)

### ISSUE THREAD

**Issue by Zorklis** [VentureCraftMods/MC-Gliders#9]
[crash-2023-02-23_02.43.24-client.txt](https://github.com/VentureCraftMods/MC-Gliders/files/10809418/crash-2023-02-23_02.43.24-client.txt)

**Comment by Suff99** [comment]
Is this 1.19.3?

**Comment by Zorklis** [comment]
yes 1.19.3

**Comment by Suff99** [comment]
Mod is currently for 1.19.2

**Comment by Zorklis** [comment]
Oh shoot, I swear I saw 1.19.3, okay thanks for solving my confusion
